### PR TITLE
Make storyshots work

### PR DESCRIPTION
**Pull request by igor-dv**
https://github.com/storybooks/storybook/issues/4778

The main issue is to make storyshots running for `ng test`.
When configuring this to work directly with jest, it makes the everything easier.

### CODE REVIEW

**Review by x1c0 — APPROVED** [review]
Hey man you're the best! I'll try this now! 👍

**Comment by x1c0** [comment]
how do you run the tests? I tried with: `npx jest` `ng test` but no success

**Comment by igor-dv** [comment]
In you repo I've run with `npm run test`

**Comment by x1c0** [comment]
image

they all failed, did you forget maybe to push some file? did you not update the angular.json config file?

**Comment by igor-dv** [comment]
Hmm. will check

**Comment by igor-dv** [comment]
Try adding `cross-env` package and setting it like this:
```json
"test": "cross-env NODE_ENV=test ng test",
```

Probably you will need to clear the jest's cache (or temporary set `cache: false` in the `jest.config.js`)

Somehow `ng test` doesn't set NODE_ENV to **test**, and babel is not kicked in for the right environment 🤷‍♂️  

image

**Comment by x1c0** [comment]
Ah.. makes sense! It's working now! Thank you so much @igor-dv!

**Comment by x1c0** [comment]
anyhow, the only way I got it working is leaving the cache set to false.. not sure why. I'll push it to master

**Comment by igor-dv** [comment]
The cache is located somewhere in **node_modules** by default. You can set `cacheDir` in the jest config to somewhat visible place (`.cache/jest` for example), and in some cases just delete the dir, jest will recreate it.

**Comment by x1c0** [comment]
Interesting, I did that -> `cacheDirectory: './.cache',` and removed the `cache: false` and now it always work 🤔

**Comment by igor-dv** [comment]
Yeah, it makes sense. This cache is containing a precompiled code of the imported modules. When there is something broken, the cache remains and updated only when you change the actual files. When you added something to package.json, jest doesn't know that the test related files have changed. When you replace the cache dir, jest started to cache everything again to a new location, but this time you already have a NODE_ENV=test, and everything works.

**Pull request merged**
